# Additional rules for the examples:

OCAMLRPCGEN = ocamlrpcgen

.SUFFIXES: .x .astamp .cstamp .sstamp .s2stamp

.x.astamp:
	$(OCAMLRPCGEN) -aux $(RPCGEN_AUX_OPTIONS) $<
	touch $@

.x.cstamp:
	$(OCAMLRPCGEN) -clnt $(RPCGEN_CLIENT_OPTIONS) $<
	touch $@

.x.sstamp:
	$(OCAMLRPCGEN) -srv $(RPCGEN_SERVER_OPTIONS) $<
	touch $@

.x.s2stamp:
	$(OCAMLRPCGEN) -srv2 $(RPCGEN_SERVER_OPTIONS) $<
	touch $@
