TOP_DIR=../..

PKGNAME = netshm
OBJECTS = netshm.cmo netshm_data.cmo netshm_hashtbl.cmo netshm_array.cmo
DOBJECTS = netshm.mli netshm_data.mli netshm_hashtbl.mli netshm_array.mli \
	   netshm_intro.txt

INCLUDES += $(INC_NETSYS)

include $(TOP_DIR)/Makefile.rules

include depend
