TOP_DIR=../..

PKGNAME  = rpc-xti
ARCHIVE  = rpc_xti
OBJECTS  = rpc_xti_client.cmo
COBJECTS = rpcxti.o
DOBJECTS = rpc_xti_client.mli

INCLUDES += $(INC_RPC)

include $(TOP_DIR)/Makefile.rules

include depend
