.PHONY: all
all:
	@echo Invoke a toploop and load one of the *.ml files into it.

.PHONY: CLEAN
CLEAN: clean

.PHONY: clean
clean:
	rm -f *.cmi *.cmo *.cma *.cmx *.o *.a *.cmxa

.PHONY: distclean
distclean: clean
	rm -f *~
